Traceback (most recent call last):
  File "C:\Users\aparn\anaconda3\envs\opened\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\aparn\anaconda3\envs\opened\Lib\site-packages\nbclient\client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aparn\anaconda3\envs\opened\Lib\site-packages\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aparn\anaconda3\envs\opened\Lib\asyncio\base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\aparn\anaconda3\envs\opened\Lib\site-packages\nbclient\client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "C:\Users\aparn\anaconda3\envs\opened\Lib\site-packages\nbclient\client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\aparn\anaconda3\envs\opened\Lib\site-packages\nbclient\client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
Fs = 20     # unit: kHz
Nsamples = 100
#F = #your code here # freq axis 0..10 kHz

#G = #your code here    # Let G = 1 only for 0..1 kHz
#g = #your code here

# frequency domain
plt.figure(figsize=(10,4))
plt.subplot(121)
plt.plot(#your code here)
plt.xlabel('F [kHz]')
plt.ylabel('Amplitude')

# time domain, plot the normalized amplitude (max=1)
t = #your code here
plt.subplot(122)
plt.plot(#your code here);
plt.xlabel('t [ms]')
plt.ylabel('Amplitude [normalized]')
------------------


[1;36m  Cell [1;32mIn[5], line 12[1;36m[0m
[1;33m    plt.xlabel('F [kHz]')[0m
[1;37m    ^[0m
[1;31mSyntaxError[0m[1;31m:[0m invalid syntax. Perhaps you forgot a comma?


